# Generated by Django 5.2.17 on 2026-09-28 18:57

import apps.league.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("maps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=40)),
            ],
            options={
                "ordering": ["stage", "name"],
            },
        ),
        migrations.CreateModel(
            name="ScoringRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80, unique=True)),
                (
                    "placement_points",
                    models.JSONField(
                        default=apps.league.models.default_placement_points,
                        help_text='Placement -> points, e.g. {"1": 12, "2": 9}. Missing placements get default_points.',
                    ),
                ),
                ("default_points", models.IntegerField(default=0)),
                ("points_per_kill", models.IntegerField(default=1)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80, unique=True)),
                ("tag", models.CharField(blank=True, max_length=12)),
                ("slug", models.SlugField(max_length=90, unique=True)),
                ("logo", models.FileField(blank=True, upload_to="teams/logos/")),
                (
                    "primary_color",
                    models.CharField(blank=True, help_text="#RRGGBB", max_length=7),
                ),
                (
                    "secondary_color",
                    models.CharField(blank=True, help_text="#RRGGBB", max_length=7),
                ),
                ("socials", models.JSONField(blank=True, default=dict)),
                ("is_league_member", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("starts_on", models.DateField(blank=True, null=True)),
                ("ends_on", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "tiebreakers",
                    models.JSONField(
                        default=apps.league.models.default_tiebreakers,
                        help_text="Ordered list from ['total_points', 'booyahs', 'kills', 'placement_points', 'last_match']",
                    ),
                ),
                (
                    "scoring_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seasons",
                        to="league.scoringrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-starts_on", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("GROUP", "Group stage"),
                            ("KNOCKOUT", "Knockout"),
                            ("FINAL", "Final"),
                        ],
                        default="GROUP",
                        max_length=10,
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="league.season",
                    ),
                ),
            ],
            options={
                "ordering": ["season", "order"],
                "unique_together": {("season", "name")},
            },
        ),
        migrations.CreateModel(
            name="MatchDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveIntegerField()),
                ("date", models.DateField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=120)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="match_days",
                        to="league.group",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_days",
                        to="league.stage",
                    ),
                ),
            ],
            options={
                "ordering": ["stage", "number"],
                "unique_together": {("stage", "group", "number")},
            },
        ),
        migrations.AddField(
            model_name="group",
            name="stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="league.stage",
            ),
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("game_uid", models.BigIntegerField(unique=True)),
                ("current_name_raw", models.CharField(max_length=80)),
                ("display_name", models.CharField(max_length=80)),
                ("search_name", models.CharField(db_index=True, max_length=80)),
                ("country", models.CharField(blank=True, max_length=2)),
                (
                    "current_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="players",
                        to="league.team",
                    ),
                ),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.AddField(
            model_name="group",
            name="teams",
            field=models.ManyToManyField(
                blank=True, related_name="league_groups", to="league.team"
            ),
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.PositiveIntegerField(help_text="Order within the match day"),
                ),
                (
                    "game_match_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("game_map_id", models.IntegerField(blank=True, null=True)),
                ("room_name", models.CharField(blank=True, max_length=120)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("duration_s", models.FloatField(blank=True, null=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PROCESSING", "Processing"),
                            ("NEEDS_REVIEW", "Needs review"),
                            ("PUBLISHED", "Published"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                (
                    "safe_zones",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Raw SafeZone files [{x, z, at}], reference only",
                    ),
                ),
                ("vod_url", models.URLField(blank=True)),
                (
                    "map",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches",
                        to="maps.map",
                    ),
                ),
                (
                    "match_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matches",
                        to="league.matchday",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "matches",
                "ordering": ["match_day", "number"],
                "unique_together": {("match_day", "number")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="group",
            unique_together={("stage", "name")},
        ),
        migrations.CreateModel(
            name="TeamAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("in_game_name", models.CharField(max_length=80)),
                (
                    "season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_aliases",
                        to="league.season",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="league.team",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("in_game_name", "season"),
                        name="unique_alias_per_season",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("season__isnull", True)),
                        fields=("in_game_name",),
                        name="unique_global_alias",
                    ),
                ],
            },
        ),
    ]
