# Generated by Django 5.2.17 on 2026-09-28 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_feature_invite_plan_staffprofile_membership_and_more"),
        ("league", "0002_default_scoring_rule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="The site account linked to this game UID",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="player",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                help_text="League teams get the league_team plan automatically",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teams",
                to="accounts.plan",
            ),
        ),
        migrations.CreateModel(
            name="RosterEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        blank=True, help_text="IGL, rusher, sniper...", max_length=40
                    ),
                ),
                ("joined_on", models.DateField(blank=True, null=True)),
                ("left_on", models.DateField(blank=True, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_entries",
                        to="league.player",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_entries",
                        to="league.season",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_entries",
                        to="league.team",
                    ),
                ),
            ],
            options={
                "ordering": ["season", "team", "player__display_name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("left_on__isnull", True)),
                        fields=("player", "season"),
                        name="one_active_roster_entry_per_season",
                    )
                ],
            },
        ),
    ]
