# Generated by Django 5.2.17 on 2026-09-28 18:57

import apps.ingest.parsers.filenames
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("league", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADING", "Uploading"),
                            ("GROUPING", "Reading files"),
                            ("READY", "Ready to confirm"),
                            ("PROCESSING", "Processing"),
                            ("DONE", "Done"),
                            ("FAILED", "Failed"),
                        ],
                        default="UPLOADING",
                        max_length=12,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                ("preview", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="upload_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "upload batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ParseRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("OK", "OK"),
                            ("WARNINGS", "OK with warnings"),
                            ("FAILED", "Failed"),
                        ],
                        default="RUNNING",
                        max_length=10,
                    ),
                ),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("sources", models.JSONField(blank=True, default=dict)),
                ("counts", models.JSONField(blank=True, default=dict)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("error", models.TextField(blank=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parse_runs",
                        to="league.match",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parse_runs",
                        to="ingest.uploadbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_name", models.CharField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("MATCH_ID", "MATCH_ID"),
                            ("SAFE_ZONE", "SAFE_ZONE"),
                            ("MATCH_RESULT", "MATCH_RESULT"),
                            ("REPLAY_JSON", "REPLAY_JSON"),
                            ("REPLAY_BIN", "REPLAY_BIN"),
                            ("DEBUGGER", "DEBUGGER"),
                            ("UNKNOWN", "UNKNOWN"),
                        ],
                        default=apps.ingest.parsers.filenames.FileKind["UNKNOWN"],
                        max_length=16,
                    ),
                ),
                (
                    "game_match_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("file_timestamp", models.DateTimeField(blank=True, null=True)),
                ("storage_key", models.CharField(max_length=500)),
                ("size", models.BigIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, db_index=True, max_length=64)),
                (
                    "parse_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("OK", "Read"),
                            ("WARNINGS", "Read with warnings"),
                            ("FAILED", "Could not read"),
                            ("SKIPPED", "Stored only"),
                            ("DUPLICATE", "Same file already uploaded"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("parse_report", models.JSONField(blank=True, default=dict)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="ingest.uploadbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["batch", "original_name"],
            },
        ),
        migrations.CreateModel(
            name="DebuggerBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game_match_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("game_map_id", models.IntegerField(blank=True, null=True)),
                ("start_line", models.PositiveIntegerField()),
                ("end_line", models.PositiveIntegerField(blank=True, null=True)),
                ("byte_start", models.BigIntegerField()),
                (
                    "byte_end",
                    models.BigIntegerField(help_text="Exclusive; start of the next block or EOF"),
                ),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("summary", models.JSONField(blank=True, default=dict)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="ingest.uploadedfile",
                    ),
                ),
            ],
            options={
                "ordering": ["file", "start_line"],
            },
        ),
    ]
