# Generated by Django 5.2.17 on 2026-09-28 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("league", "0003_player_user_team_plan_rosterentry"),
        ("maps", "0003_calibration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamRotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AUTO", "Auto draft"),
                            ("DRAFT", "Edited by staff"),
                            ("CONFIRMED", "Confirmed"),
                        ],
                        default="AUTO",
                        max_length=10,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rotations",
                        to="league.match",
                    ),
                ),
                (
                    "plotted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rotations",
                        to="league.team",
                    ),
                ),
            ],
            options={
                "ordering": ["match", "team__name"],
                "unique_together": {("match", "team")},
            },
        ),
        migrations.CreateModel(
            name="RotationPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "checkpoint",
                    models.CharField(
                        choices=[
                            ("DROP", "Drop"),
                            ("ZONE_1", "Zone 1"),
                            ("ZONE_2", "Zone 2"),
                            ("ZONE_3", "Zone 3"),
                            ("ZONE_4", "Zone 4"),
                            ("ZONE_5", "Zone 5"),
                            ("ZONE_6", "Zone 6"),
                            ("ZONE_7", "Zone 7"),
                            ("ZONE_8", "Zone 8"),
                            ("FINAL", "Final position"),
                            ("ELIMINATED", "Eliminated"),
                            ("EXTRA", "Extra point"),
                        ],
                        max_length=12,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("x", models.FloatField()),
                ("z", models.FloatField()),
                ("game_time_s", models.FloatField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Plotted by staff"),
                            ("AUTO", "Auto from match events"),
                        ],
                        default="MANUAL",
                        max_length=8,
                    ),
                ),
                (
                    "evidence",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Auto points: what they came from, e.g. {"kills": 2}',
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="maps.maparea",
                    ),
                ),
                (
                    "rotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="rotations.teamrotation",
                    ),
                ),
            ],
            options={
                "ordering": ["rotation", "order", "pk"],
            },
        ),
    ]
