# Generated by Django 5.2.17 on 2026-09-28 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0003_player_user_team_plan_rosterentry"),
        ("rotations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_id", models.BigIntegerField()),
                ("start_s", models.FloatField()),
                ("step_s", models.FloatField()),
                ("points", models.JSONField()),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="league.match",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracks",
                        to="league.player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracks",
                        to="league.team",
                    ),
                ),
            ],
            options={
                "ordering": ["match", "team", "entity_id"],
                "unique_together": {("match", "entity_id")},
            },
        ),
    ]
