# Generated by Django 5.2.17 on 2026-09-29 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0003_player_user_team_plan_rosterentry"),
        ("rotations", "0002_player_track"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReplayObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("PLAYER_UAV", "Player UAV"),
                            ("GENERAL_UAV", "General UAV"),
                            ("BOLT_MAKER", "Bolt Maker"),
                        ],
                        max_length=16,
                    ),
                ),
                ("owner_entity", models.BigIntegerField(blank=True, null=True)),
                ("start_s", models.FloatField()),
                ("end_s", models.FloatField()),
                ("x", models.FloatField()),
                ("z", models.FloatField()),
                (
                    "radius_m",
                    models.FloatField(
                        blank=True,
                        help_text="Metres a UAV scans around itself, or a Bolt Maker zone's radius",
                        null=True,
                    ),
                ),
                ("points", models.JSONField(default=list)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replay_objects",
                        to="league.match",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="league.player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="league.team",
                    ),
                ),
            ],
            options={
                "ordering": ["match", "start_s", "id"],
            },
        ),
    ]
