# Generated by Django 5.2.17 on 2026-10-03 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("maps", "0003_calibration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeaponName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("weapon_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=60)),
                (
                    "weapon_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AR", "Assault rifle"),
                            ("SMG", "SMG"),
                            ("SHOTGUN", "Shotgun"),
                            ("SNIPER", "Sniper"),
                            ("MARKSMAN", "Marksman rifle"),
                            ("LMG", "LMG"),
                            ("PISTOL", "Pistol"),
                            ("MELEE", "Melee"),
                            ("THROWABLE", "Throwable"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["weapon_id"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("WEAPON", "Weapon"),
                            ("ATTACHMENT", "Attachment"),
                            ("CHARACTER", "Character"),
                            ("PET", "Pet"),
                            ("UTILITY", "Utility"),
                            ("MAP", "Map, drop spot or route"),
                            ("ZONE", "Zone"),
                            ("GENERAL", "General"),
                        ],
                        max_length=12,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "body",
                    models.TextField(
                        blank=True, help_text="Plain text the coach may quote"
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Numbers such as range or duration",
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        help_text="The named place this entry is about",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge",
                        to="maps.maparea",
                    ),
                ),
                (
                    "map",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge",
                        to="maps.map",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "knowledge entries",
                "ordering": ["kind", "map", "title"],
            },
        ),
    ]
