# Generated by Django 5.2.17 on 2026-10-03 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coach", "0002_starter_entries"),
        ("league", "0003_player_user_team_plan_rosterentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoachReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "week_start",
                    models.DateField(help_text="Monday of the week the report covers"),
                ),
                (
                    "matches",
                    models.JSONField(
                        default=list,
                        help_text="[{id, label, map, played_on}] behind it",
                    ),
                ),
                ("facts", models.JSONField(default=list)),
                (
                    "tasks",
                    models.JSONField(
                        default=list, help_text="[{title, why, facts: [ids], matches}]"
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        default=list,
                        help_text="[{text, better, facts}] vs earlier weeks",
                    ),
                ),
                ("writer", models.CharField(default="template", max_length=40)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coach_reports",
                        to="league.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-week_start", "team__name"],
                "unique_together": {("team", "week_start")},
            },
        ),
    ]
