# Generated by Django 5.2.17 on 2026-10-03 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coach", "0003_coachreport"),
        ("league", "0003_player_user_team_plan_rosterentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="CounterPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start", models.DateField()),
                (
                    "matches",
                    models.JSONField(
                        default=list, help_text="The opponent's matches: [{id, label, map}]"
                    ),
                ),
                ("facts", models.JSONField(default=list)),
                (
                    "plays",
                    models.JSONField(
                        default=list, help_text="[{title, why, facts: [ids], matches}]"
                    ),
                ),
                ("head_to_head", models.JSONField(default=dict)),
                ("writer", models.CharField(default="template", max_length=40)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "opponent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="league.team",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counter_plans",
                        to="league.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-week_start", "opponent__name"],
                "unique_together": {("team", "opponent", "week_start")},
            },
        ),
    ]
