# Generated by Django 5.2.17 on 2026-10-03 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coach", "0004_counterplan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgeentry",
            name="conflicts",
            field=models.TextField(
                blank=True, help_text="Where sources (or our data) disagree"
            ),
        ),
        migrations.AddField(
            model_name="knowledgeentry",
            name="origin",
            field=models.CharField(
                choices=[
                    ("STAFF", "Written by staff"),
                    ("RESEARCH", "Researched online"),
                ],
                default="STAFF",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="knowledgeentry",
            name="patch",
            field=models.CharField(
                blank=True,
                help_text="Game patch it applies to, e.g. OB55",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="knowledgeentry",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="knowledgeentry",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="knowledgeentry",
            name="sources",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[{title, url, publisher, published, accessed}]",
            ),
        ),
        migrations.AddField(
            model_name="knowledgeentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="APPROVED",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="knowledgeentry",
            name="weak_reason",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="knowledgeentry",
            name="weak_sources",
            field=models.BooleanField(default=False),
        ),
    ]
