# Generated by Django 5.2.17 on 2026-10-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coach", "0006_load_research"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "feature",
                    models.CharField(help_text="report or counter", max_length=20),
                ),
                ("provider", models.CharField(max_length=20)),
                ("model", models.CharField(max_length=60)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("ok", models.BooleanField(default=True)),
                ("error", models.CharField(blank=True, max_length=300)),
                (
                    "items",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Items asked for"
                    ),
                ),
                (
                    "kept",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Items that passed the checks"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
