# Generated by Django 5.2.17 on 2026-10-08 14:50

from django.db import migrations, models

# Grenade launchers count for Top grenader (Habeeb, 2026-10-08): M79, MGL140, FGL-24.
LAUNCHERS = [23, 31, 196]


def mark_launchers(apps, schema_editor):
    WeaponName = apps.get_model("coach", "WeaponName")
    WeaponName.objects.filter(weapon_id__in=LAUNCHERS, weapon_class__in=["", "OTHER"]).update(
        weapon_class="EXPLOSIVE"
    )


def unmark_launchers(apps, schema_editor):
    WeaponName = apps.get_model("coach", "WeaponName")
    WeaponName.objects.filter(weapon_id__in=LAUNCHERS, weapon_class="EXPLOSIVE").update(
        weapon_class="OTHER"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("coach", "0007_aiusage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weaponname",
            name="weapon_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AR", "Assault rifle"),
                    ("SMG", "SMG"),
                    ("SHOTGUN", "Shotgun"),
                    ("SNIPER", "Sniper"),
                    ("MARKSMAN", "Marksman rifle"),
                    ("LMG", "LMG"),
                    ("PISTOL", "Pistol"),
                    ("MELEE", "Melee"),
                    ("THROWABLE", "Throwable"),
                    ("EXPLOSIVE", "Explosive launcher (M79, grenadier)"),
                    ("OTHER", "Other"),
                ],
                max_length=10,
            ),
        ),
        migrations.RunPython(mark_launchers, unmark_launchers),
    ]
