# Generated by Django 5.2.17 on 2026-09-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Map",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=60, unique=True)),
                ("slug", models.SlugField(max_length=60, unique=True)),
                (
                    "game_map_id",
                    models.IntegerField(
                        blank=True,
                        help_text="MapID / map_id as written in the logs",
                        null=True,
                        unique=True,
                    ),
                ),
                ("image", models.FileField(blank=True, upload_to="maps/")),
                ("image_width", models.PositiveIntegerField(blank=True, null=True)),
                ("image_height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "transform",
                    models.JSONField(
                        blank=True,
                        help_text="Affine transform world (x, z) -> image pixels",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
