# Generated by Django 5.2.17 on 2026-09-28 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0002_seed_maps"),
    ]

    operations = [
        migrations.AddField(
            model_name="map",
            name="calibrated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="map",
            name="calibration_error",
            field=models.FloatField(
                blank=True,
                help_text="RMS pixel error of the calibration points",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="map",
            name="image",
            field=models.ImageField(
                blank=True,
                height_field="image_height",
                upload_to="maps/",
                width_field="image_width",
            ),
        ),
        migrations.CreateModel(
            name="CalibrationPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(blank=True, max_length=80)),
                ("world_x", models.FloatField()),
                ("world_z", models.FloatField()),
                ("pixel_x", models.FloatField()),
                ("pixel_y", models.FloatField()),
                (
                    "map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calibration_points",
                        to="maps.map",
                    ),
                ),
            ],
            options={
                "ordering": ["map", "pk"],
            },
        ),
        migrations.CreateModel(
            name="MapArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                (
                    "polygon",
                    models.JSONField(
                        help_text="[[x, z], ...] world coordinates, at least 3"
                    ),
                ),
                ("centre_x", models.FloatField()),
                ("centre_z", models.FloatField()),
                (
                    "map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas",
                        to="maps.map",
                    ),
                ),
            ],
            options={
                "ordering": ["map", "name"],
                "unique_together": {("map", "name")},
            },
        ),
    ]
