# Generated by Django 5.2.17 on 2026-10-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0003_calibration"),
    ]

    operations = [
        migrations.AddField(
            model_name="maparea",
            name="note",
            field=models.TextField(
                blank=True, help_text="Where a suggested outline came from"
            ),
        ),
        migrations.AddField(
            model_name="maparea",
            name="status",
            field=models.CharField(
                choices=[("CONFIRMED", "Confirmed"), ("SUGGESTED", "Suggested")],
                default="CONFIRMED",
                max_length=10,
            ),
        ),
    ]
